#!/bin/bash
export MYSQL_USER_NAME=bacadmin 
export MYSQL_USER_PWD=12345678 
export MYSQL_USER_DB=bacadmin_changepw

service mysql start

mysql --defaults-file=/my.cnf -e "CREATE USER  $MYSQL_USER_NAME @'%' IDENTIFIED BY '$MYSQL_USER_PWD';GRANT USAGE ON *.* TO $MYSQL_USER_NAME @'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;CREATE DATABASE IF NOT EXISTS $MYSQL_USER_NAME;GRANT ALL PRIVILEGES ON $MYSQL_USER_NAME.* TO $MYSQL_USER_NAME @'%';FLUSH PRIVILEGES;"
